flash
Tested with 
```bash
flash --hostname pi5 http://assets.hypriot.com/hypriot-rpi-20150329-140334.img.zip
ssh pi@pi5.local
```
=> fix setting hostname by removing spaces

Darwin/flash, Linux/flash
With this PR you can flash the same remote SD image multiple times without downloading it everytime.
The `flash` script caches the extracted SD image in `/tmp`. The next call of the `flash` script re-uses this cached SD image.
So flashing for multiple Pi's is now much easier and faster.
```bash
$ flash --hostname pi1 http://downloads.hypriot.com/hypriot-rpi-20150416-201537.img.zip
$ flash --hostname pi2 http://downloads.hypriot.com/hypriot-rpi-20150416-201537.img.zip
$ flash --hostname pi3 http://downloads.hypriot.com/hypriot-rpi-20150416-201537.img.zip
```
Connects to #3.
=> use cached image if already downloaded and extracted

Darwin/flash, Linux/flash
I tried to download the official Raspbian LITE SD image with this tool
and found that it does not handle https links.
This PR fixes it.
=> Download from https links as well

Darwin/flash, Linux/flash
Hi, this script is really convenient and I like this. But I had a problem.
I have an Wi-Fi access point, named "ham airmac" and the 'flash' script failed to write wifi_ssid setting to config, like below log. So I modified the scripts to allow the situation. I only actually tested Darwin version though.
```
$ flash --ssid "ham airmac" --password "xxxxxx" --hostname hypriot http://downloads.hypriot.com/hypriot-rpi-20151115-132854.img.zip
....
Is /dev/disk2s1 correct? y
Unmounting disk2 ...
Unmount of all volumes on disk2 was successful
Unmount of all volumes on disk2 was successful
Flashing /tmp/hypriot-rpi-20151115-132854.img to disk2 ...
Password:
1.4GiB 0:00:27 [52.4MiB/s] [==============================================================================================================>] …
```
=> allow whitespaces in WIFI_SSID

Darwin/flash, Linux/flash
Instead of just checking the file extension of the local file for `.zip` get the file type with the `file` utility and unzip it.
Fixes #28
=> Check file type instead of extension to run unzip

Darwin/flash
Fixes #38 recognize SD card without FAT partition
fixes #29 work with mounted .dmg files
Doesn't "hang" after flashing an SD card image without FAT partition, just abort after 5 seconds and unmount everything without occidentalis.txt/config.txt features.
=> Recognize SD card without FAT partition

Darwin/flash
This allows downloading, extracting and flashing xz compressed images.
The xz does not remove the original file, eg. if you have local .xz files you want to keep.
=> Allow xz compressed images

Darwin/flash
Flashing one of our locally built sd-card-*-dirty.img.zip files from the hypriot/image-builder-* repos lead in a caching problem.
This PR fixes it by always extracting the ZIP file.
=> Use cache only for downloads, always extract ZIP

Linux/flash
This PR is based on top of the idea of https://github.com/hypriot/flash/pull/21. This PR now correctly selects SD cards with `mmcblk...` identifier as well as USB-SD reader identified via `sdb...` when using the flash tool in Linux.
@firecyberice Please test this on your machine.
=> Filter correct disk ID in Linux

Darwin/flash, Linux/flash
For our new HypriotOS SD card images the `flash` script start supporting [device-init](https://github.com/hypriot/device-init).
If the FAT partition contains a file `device-init.yaml` then the option `--hostname` already works, also the `--config` option to copy a whole device-init.yaml into this partition.
Tested on Mac.
=> Add support for /boot/device-init.yaml

Darwin/flash
because if gnuutils are loaded these command fail so use absolute paths.
The cache check is failing because it is looking for the .zip file and it is deleted after you unzip it.
=> correct check for cached download and absolute paths for dd and stat

README.md, Vagrantfile
For Mac users there is a Vagrant box to spin up a Linux test environment for the `Linux/flash` script.
Found a good solution to prevent duplicate usb filters from being generated in NextThingCo/CHIP-SDK#15
=> Add VirtualBox Vagrant test environment for Mac users

Darwin/flash
Use an absolute path to sed to avoid problems if the GNU sed binary is installed on a Mac.
Fixes #48
=> Use absolute path to sed to avoid gnu-sed

README.md
Fix markdown errors as identified by atom-linter 
See https://atom.io/packages/linter-markdown
Add wget install for those on a Mac
=> Fix Markdown errors and add wget install on Mac

Darwin/flash, Linux/flash, README.md
This PR with hypriot/image-builder-rpi#55 enables setting the wifi ssid and password for newer HypriotOS SD card images. The /boot/device-init.yaml file in the SD card image must be prepared with a wlan0 setting that can be enabled by the flash tool.
Fixes #58
=> Set the wlan0 ssid and password in device-init.yaml if given

Linux/flash
Device paths won't change after being mounted, so udev has nothing to
do. Aside from when we change the partition table via dd, we don't need
to do udevadm settles.
=> Remove unnecessary udevadm settle

Linux/flash
Ran into problem with flash command recently where it was unable to finish customizing the image.
I got the following on the command line:
```
Mounting /dev/mmcblk0p1 to customize...
mount: you must specify the filesystem type
```
Not sure why I've just started seeing it, but this seems to fix it.
=> Fixed mount complaint on Linux

README.md
As different Linux distributions have the different methods of software installation, this PR clarifies that the described method is specific for Debian/Ubuntu-based distributions.
=> Clarifying Linux distros instructions

Linux/flash
Ran into this issue when trying to flash the ODROID ext4 only image. This should make it more flexible as long as `blkid` is an OK dependency.
=> Added filesystem autodetect in case of non-vfat boot

README.md
Low hanging fruit. The `--help` output of the `Usage` section does not include the clusterlab flag. This pull request adds the current output from running `./flash --help`.
=> Update README.md usage section to include clusterlab

Darwin/flash
Fixes a small typo when the flashing is unsuccessful.
=> Fixes typo in error message

Darwin/flash
The Linux script has a `-d` flag to allow a user to select a device. This PR allows users to select the device on OS X as well.
=> Allow users on Darwin to select device

Linux/flash
This sets the `${boot}` temporary mount point based upon the PID of the flash instance which is running. This allows for more than one instance to run at the same time. Additionally, on successful run it removes the temporary mount point.
This helps reduce the pain of flashing a cluster ;-)
=> Update flash to allow concurrent runs

Darwin/flash, Linux/flash
When a user provided a malformed url or the server return a file "Not Found" error, the script continued to execute.
the --fail option passed to curl prevent this behavior and result in a proper error handling.
have a look at the following example:
```
./flash --hostname node01 https://github.com/hypriot/image-builder-rpi/releases/download/v1.4.0/hypriotos-rpi-v1.4.0.im
/usr/bin/curl
Downloading https://github.com/hypriot/image-builder-rpi/releases/download/v1.4.0/hypriotos-rpi-v1.4.0.im ...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```
=> fail early when url is malformed or the server return an error code

Linux/flash
A tiny fix which allows the script to work on systems which don't install bash in `/bin/bash`.
Thanks for such a great tool.
=> Remove assumed of location of bash

Linux/flash
Simple patch for partition naming scheme on loop devices (e.g. /dev/loop0p1). I might later make a patch which handles creating the loop device automatically when a non-/dev/ location is provided.
Fixes #102
=> Added support for loop device partitions

README.md, sample/no-uart-config.txt, sample/wifi-device-init.yml, sample/wifi-user-data.yml
- Describe the cloud-init config with user-data
- Add samples folder for onboard WiFi (cloud-init and device-init) and config.txt to turn off UART
- Remove occidentalis sample, remove AWS S3 sample
- Add more details about local development
=> Improve README and add samples

.travis.yml
Use the much cleaner `npm test` instead of `node_modules/.bin/bats --tap test` in Travis build.
=> Use npm test in Travis

flash
Fix error return of grep when no mmcblk device can be found.
=> Fix grep returning error

flash
Before this change, this wouldn't run on macOS.
=> Use predefined bs_size

flash
Block device is not displayed in Linux OS so processing can not be completed.So, Change block device with path for Linux OS
=> [#118]Change block device with path for Linux OS

.gitignore, Dockerfile
This fixes the broken CircleCI tests running in Linux containers.
Add the missing `udev` package.
=> Fix linux test, add udev package

flash
Check for WSL2 kernels and show the user a message that `flash` is not supported in WSL1 and WSL2.
Refers to #160
=> Check for WSL2

flash
I tried to flash Ubuntu 64bit, but flash didn't extract the xz archive.
```file
$ file ~/Downloads/ubuntu-18.04.4-preinstalled-server-arm64+raspi3.img.xz
/Users/stefanscherer/Downloads/ubuntu-18.04.4-preinstalled-server-arm64+raspi3.img.xz: XZ compressed data
```
This PR makes the xz compression check case insensitive.
=> Make xz compression check case insensitive

flash
Fix: 
- #169 race condition of the copy operation wasn't completed and disk couldn't be unmounted
@StefanScherer please see the issue for more context.
=> Allow graceful period for all operations to complete before unmounting #169

flash, test/cloud-init.bats, test/resources/wifi-commented-user-data.yml, test/resources/wifi-user-data.yml
added
* naive implementation of SSID/PSK settings to user-data
* basic tests to try to cover this
=> #109: wifi params to user-data

flash, test/cloud-init.bats
With this URLs can be specified instead of local files for `--bootconf`, `--config`, `--userdata`, `--metadata` and `--file`.
=> Allow to download files related to cloud-init via http(s)

flash, test/cloud-init.bats, test/resources/comment-not-in-first-line.yml, test/resources/missing-comment.yml
On macOS we already validate the user-data yaml file, but this does not include a check for the `#cloud-config` comment in the first line.
According to https://cloudinit.readthedocs.io/en/latest/topics/faq.html#how-can-i-debug-my-user-data it is one of the two top most problems. In my experience it IS the top most problem and to be honest I do not understand why this cannot be fixed in cloud-init 😅
> Two of the most common issues with user data, that also happens to be cloud-config is:
> 1. Incorrectly formatted YAML
> 2. First line does not contain #cloud-config
Helps #177 to find problems before users run into boot problems.
=> Check for #cloud-config comment in first line

flash
macos' "diskutil" reported "Read-Only Media: No" up until v10.6, but v11.0 (Big Sur) reports the same information as "Media Read-Only: No". This commit adds support for both variants.
=> Fix for macos Big Sur changes to diskutil output

test/cloud-init.bats
While building a release it turns out that one of the BATS tests fails.
=> Fix 404 test
