flash

* Remove some comments
* Remove some space around `=` sign

minor cleanup

---

flash.linux

Here's an initial linux version. I added an extra flag beyond the OS/X version -- the ability to specify the device.  Another difference is the checking to see if wget and/or s3 binaries exist....
I don't know that this will work with every flavour of linux, but I tried to make it as generic as possible.

Initial linux version

---

Darwin/flash

check for curl and aws before using these dependencies

---

README.md

Show a small example using a S3 bucket.
Connects to #11.

add S3 example

---

README.md

- Add `install curl` since it's a dependency
- Combine the command to make it shorter
@StefanScherer: Please review and merge.

Improve setup commands for Linux

---

Darwin/flash
Linux/flash
README.md

* Ported `--bootconf` to Mac, thanks to @aetherical for the contribution!
* Fixed a bug that created a `occidentalis.txt-e` file.

Ported --bootconf to Mac

---

Darwin/flash

Hi,
in my grep create colored output because of that the script is not able to locate the correct volume to flash. 
Greets,
Moddus

fix cut issue when grep uses colored output.

---

Darwin/flash

This commit helps Mac users and recognizes write protected SD cards.
Connects to #16

Recognize write protection

---

Darwin/flash
Linux/flash

Fixes #33 
@MathiasRenner please test this PR on Linux.

fixed unzipped filename resolution to exclude spaces

---

Linux/flash

This helps Linux users and recognizes write protected SD cards.
Someone has to test this on Linux.
Fixes #16

WIP: Recognize write protection on Linux

---

.editorconfig
Darwin/flash
Linux/flash

* Add an .editorconfig file for many editors to use the desired indentation.
* Use shellcheck to improve code quality
Diff it with this link to ignore white spaces: https://github.com/hypriot/flash/pull/51/files?w=1

Cleanup code, indentation, shellcheck

---

AUTHORS
Linux/flash

Hi, thanks for the great project! These are just a few things I noticed while running the flash utility.

A few assorted fixes and cleanups

---

README.md

While trying to run the flash utility I got a notification that hdparm is required before the flash utility can be run

add hadparm to the dependencies (on linux at least)

---

README.md

Update README description to support SD card images of any kind

---

README.md

Remove wget instructions

---

Linux/flash

re-read disk partition table after write on Linux

---

README.md

@StefanScherer Please review and merge.

Add how to flash in non-interactively

---

Linux/flash

This fixes #87 on my Ubuntu 14.04 (trusty) system.
Thanks!

Adding sudo for the hdparm -z use on Linux.

---

Linux/flash

Reorder some checks, fix check for Darwin, add check for WSL, check Linux + linux.

Improve platform checks

---

.travis.yml
Darwin/flash
Linux/flash
README.md
package.json
test/cloud-init.bats
test/darwin.bats
test/device-init.bats
test/flash-url.bats
test/raspbian.bats
test/test_helper.bash
test/usage.bats

Turn on Travis again to have a macOS build agent, Circle does not have matrix builds or both Linux and macOS in one project.

Add macOS test

---

Linux/flash
README.md

When playing with different configurations, sometimes it is useful not to have to re-write the image every time. This not only saves time but also some unneeded writes to the SD card. Therefore, I propose to add an option to configure/reconfigure a pre-existing image.

Create a new switch for configuring an already deployed image

---

README.md

The config.txt documentation has been moved

update link for the config.txt documentation

---

README.md
flash

Adds the ability to specify a custom file to be copied to the boot partition when flashing. I use this to write some configuration (docker-compose files and bash scripts) used for my custom host initialization.

Copy custom file to /boot when flashing

---

flash
test/fake-hwclock.bats

Helper for hypriot/image-builder-rpi#334

set fake-hwclock
